### ISSUE TITLE
add distributions

### ISSUE THREAD

**Issue by goldingn** [goldingn/greta#1]
Only a couple are implemented so far. I should get round to adding more before too long.

If you're reading this and there's a particular distribution you're after, please comment below and Ill try to get to that as a priority

**Comment by goldingn** [comment]
HMC requires gradients for the joint density w.r.t all random variables that aren't defined as observed.
Gradients cannot be computed for discrete random variables.

Will therefore need to warn if random variables with discrete distributions are included, but not defined as observed.

This is probably easiest to check on construction of the dag - just need to check that discrete nodes are have the fixed flag set to TRUE.

Trying to detect this during the interactive phase will be more pain than it's worth.

**Comment by goldingn** [comment]
Here's the initial shopping list for distributions, in order of priority:

- [x] Normal
- [x] Log-normal
- [ ] Bernoulli
- [ ] Binomial
- [ ] Poisson
- [ ] Gamma
- [ ] Exponential
- [ ] Negative binomial
- [ ] Student
- [ ] Weibull
- [ ] Beta
- [ ] Chi-square
- [ ] Double exponential
- [ ] F
- [ ] Generalized gamma 
- [ ] Noncentral hypergeometric
- [ ] Logistic
- [ ] Noncentral Chi-square
- [ ] Pareto

**Comment by goldingn** [comment]
dag construction now checks for unfixed discrete stochastic nodes

**Comment by jwdink** [comment]
As discussed on twitter, will put in a vote for this: https://www.rdocumentation.org/packages/flexsurv/versions/1.0.0/topics/Survspline

Can be thought of as a generalization of the (PH parameterization of the) Weibull distribution, where instead of hazard increasing/decreasing w/time, one can model it as an arbitrary spline function of time.

My time will be extremely constrained for the next few weeks, but would love to help contribute soon.

**Comment by goldingn** [comment]
This looks cool!

I might add the traditional Weibull to the standard distributions, then we can put a survspline implementation in a module. 

I'm aiming for the basic greta distributions to match the distributions in R base & stats, BUGS, and JAGS. Too many unfamiliar distributions in that list and it'll get hard to navigate. 

Maybe a survspline implementation could go in either an 'extra distributions' module, or a 'survival' module.

**Comment by jwdink** [comment]
That makes sense. A survival module would also be a great place to add functionality for censoring, truncation, etc.

**Comment by goldingn** [comment]
Yeah, great idea!

**Comment by goldingn** [comment]
I'll start a new issue for that module now

**Comment by TonyLadson** [comment]
Hi,
Thanks for all your work so far.  
I'm interested in extreme value modelling in hydrology.  Commonly used distributions are:
GEV, Gumbel, Log Pearson III, Log Normal, Generalised Pareto, Exponential.  
Also bivariate extreme value distributions e.g. Gumbel type B.

**Comment by goldingn** [comment]
Cool, thanks!

I'm trying to make the parameter names and density definitions match up as much as possible with commonly used R density functions. E.g. `greta::normal()` uses the same parameters names etc. as `stats::dnorm()`. My order of preference for 'canonical' distribution definitions is `stats` > R's recommended packages, like `MASS` > other commonly used packages > wikipedia or some other commonly read source > less commonly used packages.

I'm not familiar with some of these (though lognormal and exponential are already implemented), so **could you please point me to some widely used R implementations of these?**.

**Comment by TonyLadson** [comment]
Hi,

Thanks for this.

Package FAdist

FAdist::GAMMA3 (aka Pearson type III)
FAdist::GenPARETO
FAdist::GEV 
FAdist::GUMBEL
FAdist::LGAMMA3 (Log-Pearson  type III)

There is also packages: lmomco, evd, gumbel, evir

**Comment by goldingn** [comment]
That's really helpful, thank you!

**Comment by goldingn** [comment]
I've made a good run on these distributions now (on the dev branch), so closing this issue for the time being. Extreme value distributions moved to a new issue for a module
