### ISSUE TITLE
Possible issue with beta() distribution

### ISSUE THREAD

**Issue by lygeorgi** [goldingn/greta#40]
Hi,

First, I would like to congratulate you on a great package. It is very convenient and user friendly. Thank you for your work!

I am running into an error when I try to execute the following code:

library(greta)
my_rate <- beta(2, 5)
my_data <- 6
likelihood(my_data) <- binomial(16, my_rate)
m <- define_model(my_rate)

> Error in -x : invalid argument to unary operator

If I substitute beta() with another distribution for my prior (ex. lognormal()), the code executes without any issues.

I am not sure whether I am doing something wrong and this is intended or it is a possible bug. 
Thank you for your help.

Best regards,
LG

**Comment by goldingn** [comment]
Thanks!

Sounds like a bug. Should be easy for me to fix though.

**Comment by goldingn** [comment]
This should now be fixed in the development branch. You can install that with:
```r
devtools::install_github('goldingn/greta@dev')
```
I'll merge it into the master branch once I've made a couple of other fixes and updates. I'll also be adding unit tests soon, which should catch bugs like these.

Thanks again for letting me know!
